<a href="https://colab.research.google.com/github/aih-2012/ML-Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lists vs Numpy Arrays:

- Numpy Arrays are faster
- Numpy Arrays take less memory space
- Numpy Arrays store data continuously/sequentially in the memory
- Numpy arrays support complex mathematical calculations
- Data types can be defined in Numpy Arrays

`import numpy as np` - For importing library in project

`arr1 = np.array([1, 2, 3, 4, 5])` - For creating numpy array object (1D)

`arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])` - For creating Numpy array object (2D)

`arr1.ndim` - For viewing number of dimensions

`arr1.dtype`  - For viewing/defining data type of array

`arr1.shape` - For viewing shape of array (rows, columns)

`np.zeros([a,b])` - For creating an all-zero array of size `(a,b)`

`np.ones([a,b])` - For creating an all-one array of size `(a,b)`

`np.full([a,b], i)` - For creating an `(a,b)` array with all values as `i`

`arr2 = arr1.copy()` - For creating a new array containing all the contents of another array

`arr1.astype()` - For converting the data type of an array

`arr2 = arr1.view()` - For creating a duplicate of an array whose changes will change the original array

`np.add(arr1, n)`, `np.subtract(arr1, n)`, `np.multiply(arr1, n)`, `np.divide(arr1, n)`, `np.sin(arr1, n)`, `np.cos(arr1, n)`, `np.tan(arr1, n)` etc. for various mathematical operations


In [1]:
import numpy as np
a = np.array([1,3,5,7,9], dtype='int32') # Numpy array with data type as 32-bit int
a

array([1, 3, 5, 7, 9], dtype=int32)

**Data** **Type**

In [2]:
a.dtype # Print the data type of numpy array

dtype('int32')

**Number of dimensions**

In [3]:
a_2d = np.array([[[1,2,3],[4,5,6]], [[3,2,1],[6,5,4]], [[7,8,9],[10,11,12]], [[9,8,7],[12,11,10]]]) # Two-dimensional numpy array
a_2d.ndim # Print dimensions of numpy array

3

**Shape**

In [4]:
a_2d.shape # Print the shape (i.e. rows, columns) of numpy array

(4, 2, 3)

In [5]:
print(a_2d[0, 1, 2]) # Print the third character (index-2) at index-1 of the first array (index-0) of a_2d

6


In [6]:
a_2d[0, 1, 0] = 7 # Assign the first character (index-0) at index-1 of the first array (index-0) of a_2d
a_2d[0, 1]

array([7, 5, 6])

In [7]:
b = np.zeros([2, 3]) # Generate an all-zero matrix of shape (2,2)
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c = np.full([4, 4], 72) # Generate a matrix where all values are 72 with size (4,5)
c

array([[72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72]])

In [9]:
# The problem with assigning variables to numpy arrays of other variables
d = np.array([[1,2,3], [4,5,6]])
e = d # Copy the 'd' array to an 'e' variable
e[0, 2] = 9 # Assign the value at index (0, 2) of 'e' array to 9
d # The array 'd' is changed to that of 'e'

array([[1, 2, 9],
       [4, 5, 6]])

In [10]:
# Solution
f = np.array([[1,2,3], [4,5,6]])
g = f.copy() # Copy the 'd' array to an 'e' variable USING NUMPY COPY() METHOD
g[0, 2] = 9 # Assign the value at index (0, 2) of 'g' array to 9
f # The array 'd' is changed to that of 'e'

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Mathematical Operations

a1 = np.array([1, 2, 3, 4, 5, 6])
b1 = np.array([7, 8, 9, 10, 11, 12])

**Addition**

In [12]:
a1+b1 # Addition

array([ 8, 10, 12, 14, 16, 18])

In [13]:
np.add(a1, b1) # Addition

array([ 8, 10, 12, 14, 16, 18])

**Subtraction**

In [14]:
a1-b1 # Subtraction

array([-6, -6, -6, -6, -6, -6])

In [15]:
np.subtract(a1, b1) # Subtraction

array([-6, -6, -6, -6, -6, -6])

**Multiplication**

In [16]:
a1*b1 # Multiply

array([ 7, 16, 27, 40, 55, 72])

In [17]:
np.multiply(a1, b1) # Multiply

array([ 7, 16, 27, 40, 55, 72])

**Division**

In [18]:
a1/b1 # Divide

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [19]:
np.divide(a1, b1) # Divide

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

**Sine**

In [20]:
np.sin(a1) # Sine

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

**Cosine**

In [21]:
np.cos(a1) # Cosine

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

**Tangent**

In [22]:
np.tan(a1) # Tangent

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])